### ISSUE TITLE
这是 3.6 的吗

### ISSUE THREAD

**Issue by danliangsky** [Sycamore0/GenshinData#9]
~~~

**Comment by Sycamore0** [comment]
yep

**Comment by danliangsky** [comment]
大佬是否知道 路径 Chinese\\VO_EQ\\VO_albedo\\vo_EQXS104_13_albedo_01.wem 是怎么hash的，能和 wwise-unpacker解包后对应上 https://github.com/mortalis13/Wwise-Unpacker
